src/pg_to_evalscript/node.py

Ensure variable name is not a number

---

README.md
src/pg_to_evalscript/conversion.py
src/pg_to_evalscript/evalscript.py
src/pg_to_evalscript/javascript_datacube/DataCube.js

closes https://github.com/openEOPlatform/openeo-pg-evalscript-converter/issues/2

Add optional parameter to disable/enable encoding result data.

---

tests/unit_tests/test_mean.py
tests/utils.py

Also fixes issues with imports of files with relative paths.

Unit tests

---

src/pg_to_evalscript/javascript_processes/min.js
src/pg_to_evalscript/javascript_processes/multiply.js
src/pg_to_evalscript/javascript_processes/sum.js
tests/unit_tests/test_min.py
tests/unit_tests/test_multiply.py
tests/unit_tests/test_sum.py

New processes and tests
- min https://git.sinergise.com/team-6/openeo-platform/-/issues/52
- sum https://git.sinergise.com/team-6/openeo-platform/-/issues/53
- multiply https://git.sinergise.com/team-6/openeo-platform/-/issues/54

Add min, sum, multiply process

---

Pipfile
README.md

I had some troubles with the commands for running the notebooks, so I added some details for alternative ways.

Add details for running notebooks in the readme

---

src/pg_to_evalscript/javascript_processes/array_contains.js
tests/unit_tests/test_array_contains.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/63

Array_contains process

---

src/pg_to_evalscript/javascript_processes/ceil.js
src/pg_to_evalscript/javascript_processes/floor.js
tests/unit_tests/test_ceil.py
tests/unit_tests/test_floor.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/65

Ceil and floor process

---

src/pg_to_evalscript/javascript_processes/ln.js
src/pg_to_evalscript/javascript_processes/log.js
tests/unit_tests/test_ln.py
tests/unit_tests/test_log.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/66

Ln and log process

---

src/pg_to_evalscript/javascript_processes/first.js
src/pg_to_evalscript/javascript_processes/last.js
tests/unit_tests/test_first.py
tests/unit_tests/test_last.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/64

First and last process

---

src/pg_to_evalscript/javascript_processes/exp.js
src/pg_to_evalscript/javascript_processes/power.js
tests/unit_tests/test_exp.py
tests/unit_tests/test_power.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/67

Exp and power process

---

src/pg_to_evalscript/javascript_processes/constant.js
src/pg_to_evalscript/javascript_processes/mod.js
src/pg_to_evalscript/javascript_processes/sort.js
tests/unit_tests/test_constant.py
tests/unit_tests/test_mod.py
tests/unit_tests/test_sort.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/82

Sort, constant, mod process

---

src/pg_to_evalscript/javascript_processes/sqrt.js
tests/unit_tests/test_sqrt.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/87

Sqrt process

---

src/pg_to_evalscript/javascript_processes/and.js
src/pg_to_evalscript/javascript_processes/or.js
tests/unit_tests/test_and.py
tests/unit_tests/test_or.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/88

And / or process

---

src/pg_to_evalscript/javascript_processes/not.js
src/pg_to_evalscript/javascript_processes/xor.js
tests/unit_tests/test_not.py
tests/unit_tests/test_xor.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/89

Xor and not process

---

src/pg_to_evalscript/javascript_processes/e.js
tests/unit_tests/test_e.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/86

add e (euler number) process and tests

---

src/pg_to_evalscript/javascript_processes/arccos.js
src/pg_to_evalscript/javascript_processes/arcsin.js
src/pg_to_evalscript/javascript_processes/arctan.js
src/pg_to_evalscript/javascript_processes/cos.js
src/pg_to_evalscript/javascript_processes/sin.js
src/pg_to_evalscript/javascript_processes/tan.js
tests/unit_tests/test_arccos.py
tests/unit_tests/test_arcsin.py
tests/unit_tests/test_arctan.py
tests/unit_tests/test_tan.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/90

add tan, arctan, arcsin, arccos processes

---

src/pg_to_evalscript/javascript_processes/clip.js
src/pg_to_evalscript/javascript_processes/extrema.js
src/pg_to_evalscript/javascript_processes/median.js
src/pg_to_evalscript/javascript_processes/sgn.js
tests/unit_tests/test_any.py
tests/unit_tests/test_clip.py
tests/unit_tests/test_cos.py
tests/unit_tests/test_extrema.py
tests/unit_tests/test_median.py
tests/unit_tests/test_sgn.py
tests/unit_tests/test_sin.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/93

Clip, sgn, extrema, median process

---

src/pg_to_evalscript/javascript_processes/arcosh.js
src/pg_to_evalscript/javascript_processes/arsinh.js
src/pg_to_evalscript/javascript_processes/artanh.js
src/pg_to_evalscript/javascript_processes/cosh.js
src/pg_to_evalscript/javascript_processes/sinh.js
src/pg_to_evalscript/javascript_processes/tanh.js
tests/unit_tests/test_arcosh.py
tests/unit_tests/test_arsinh.py
tests/unit_tests/test_artanh.py
tests/unit_tests/test_cosh.py
tests/unit_tests/test_sinh.py
tests/unit_tests/test_tanh.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/91
- `cosh` (Hyperbolic cosine): https://docs.openeo.cloud/processes/#cosh
- `sinh` (Hyperbolic sine): https://docs.openeo.cloud/processes/#sinh
- `tanh` (Hyperbolic tangent): https://docs.openeo.cloud/processes/#tanh
- `arcosh` (Inverse hyperbolic cosine): https://docs.openeo.cloud/processes/#arcosh
- `arsinh` (Inverse hyperbolic sine): https://docs.openeo.cloud/processes/#arsinh
- `artanh` (Inverse hyperbolic tangent): https://docs.openeo.cloud/processes/#artanh

Add processes for hyperbolic functions

---

src/pg_to_evalscript/javascript_processes/rearrange.js
tests/unit_tests/test_rearrange.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/95
docs: https://docs.openeo.cloud/processes/#rearrange

add rearrange process

---

src/pg_to_evalscript/javascript_processes/array_append.js
tests/unit_tests/test_array_append.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/96
docs: https://docs.openeo.cloud/processes/?#array_append

add array_append process

---

src/pg_to_evalscript/javascript_processes/product.js
tests/unit_tests/test_product.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/94
This was originally part of [this PR](https://github.com/openEOPlatform/openeo-pg-evalscript-converter/pull/36) but was now split to 2 separate PRs

Product process

---

src/pg_to_evalscript/javascript_processes/sd.js
tests/unit_tests/test_sd.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/99

Sd process

---

src/pg_to_evalscript/javascript_processes/variance.js
tests/unit_tests/test_variance.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/100

Variance process

---

src/pg_to_evalscript/javascript_processes/array_create.js
tests/unit_tests/test_array_create.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/102

Array_create process

---

src/pg_to_evalscript/javascript_processes/dimension_labels.js
tests/unit_tests/test_dimension_labels.py
tests/utils.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/101

Dimension_labels process

---

tests/unit_tests/test_add_dimension.py
tests/unit_tests/test_array_element.py
tests/unit_tests/test_dimension_labels.py
tests/unit_tests/test_filter_bands.py
tests/unit_tests/test_merge_cubes.py
tests/unit_tests/test_rename_labels.py
tests/utils.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/113

Optimize run_process and run_process_with_additional_js_code function

---

src/pg_to_evalscript/javascript_processes/array_labels.js
tests/unit_tests/test_array_labels.py
tests/utils.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/98

Array_labels process

---

src/pg_to_evalscript/javascript_processes/order.js
tests/unit_tests/test_order.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/111

Add order process

---

src/pg_to_evalscript/javascript_processes/array_contains.js
src/pg_to_evalscript/javascript_processes/array_find.js
tests/unit_tests/test_array_contains.py
tests/unit_tests/test_array_find.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/107

Array find process

---

src/pg_to_evalscript/conversion.py
src/pg_to_evalscript/javascript_processes/array_filter.js
src/pg_to_evalscript/node.py
tests/integration_tests/test_integration.py
tests/process_graphs/test_array_filter.json
tests/unit_tests/test_array_filter.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/115

Add array filter process

---

src/pg_to_evalscript/evalscript.py
src/pg_to_evalscript/javascript_datacube/DataCube.js
src/pg_to_evalscript/javascript_processes/filter_temporal.js
tests/integration_tests/test_integration.py
tests/process_graphs/test_filter_temporal.json
tests/unit_tests/test_filter_temporal.py
tests/utils.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/129

Filter temporal process

---

src/pg_to_evalscript/conversion.py
src/pg_to_evalscript/javascript_datacube/DataCube.js
src/pg_to_evalscript/javascript_processes/aggregate_temporal.js
src/pg_to_evalscript/node.py
tests/integration_tests/test_integration.py
tests/process_graphs/test_aggregate_temporal.json
tests/unit_tests/test_aggregate_temporal.py

https://git.sinergise.com/team-6/openeo-platform/-/issues/142
This PR handles intervals in "date-time" format only. We will handle intervals in "date" and "time" format (see examples in docs) separately.

Aggregate temporal process

---

src/pg_to_evalscript/javascript_datacube/DataCube.js
tests/unit_tests/test_apply_dimension.py

Closes https://git.sinergise.com/team-6/openeo-platform/-/issues/166

Fix apply_dimension
